### ISSUE TITLE
getaccounaddres() will be permanently removed in v.0.18.

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/Tip-Sugar#12]
Btw, reading the source codes of the tip bot, we are using getaccounaddres() which is deprecated already and will be permanently removed in v.0.18.
https://bitcoincore.org/en/doc/0.17.0/rpc/wallet/getaccountaddress/

reported by @aglkm
@ilmango-doge

**Comment by Nugetzrul3** [comment]
`-deprecatedrpc=accounts` Can use this when starting daemon
